
version: '3.1'
services:
  app:
    container_name: splitwise
    image: splitwise
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=splitwise
      - POSTGRES_USER=splitwise
      - POSTGRES_DB=splitwise