
version: "3.1"
services:
  dbpostgresql:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=splitwise
      - POSTGRES_USER=splitwise
      - POSTGRES_DB=splitwise
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: splitwise:latest
    network_mode: bridge
    container_name: splitwise
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - dbpostgresql
    links:
      - dbpostgresql
volumes:
  postgres-data: